####
#@valid user login 1
POST http://localhost:3003/public/auth/login HTTP/1.1
content-type: application/json

{
    "username": "tester uno",
    "password": "f!rE|ntHeH076"
}

####
#@valid user login 2

POST http://localhost:3003/public/auth/login HTTP/1.1
content-type: application/json

{
    "username": "tester deus",
    "password": "F/ippAtyF7a€"
}

####
#@valid GUEST login
POST http://localhost:3003/public/auth/guest HTTP/1.1



####
#@invalid login

POST http://localhost:3003/public/auth/login HTTP/1.1
content-type: application/json

{
    "username": "tester invalid",
    "password": "drowssap"
}

####