####
#@valid login 1
POST http://localhost:3003/public/login HTTP/1.1
content-type: application/json

{
    "username": "tester uno",
    "password": "f!rE|ntHeH076"
}

####
#@valid login 2

POST http://localhost:3003/public/login HTTP/1.1
content-type: application/json

{
    "username": "tester deus",
    "password": "F/ippAtyF7a€"
}

####
#@invalid login

POST http://localhost:3003/public/login HTTP/1.1
content-type: application/json

{
    "username": "tester invalid",
    "password": "drowssap"
}

####