####
#@valid General Diagnosis

POST http://localhost:3003/api/protected/symptoms/general HTTP/1.1
content-type: application/json

{
    "symptoms": ["wrist pain, knee joints frozen"]
}

####
#@valid Specific Diagnosis
POST http://localhost:3003/api/protected/symptoms/specific HTTP/1.1
content-type: application/json

{
    "symptoms": ["shoulders stiff, spine swollen"]
}

####
